Initial implementation of the Operator Interface class
AusTINCANsProgrammingTeam/2022Swerve pull request #4
Opened 2022-09-29 15:09 UTC by zbrotherton2158

2022-10-07 00:06 UTC, azvanderpas requested changes
Mainly just want some more documentation on some of the math. Then this is good to go

2022-10-07 00:06 UTC, azvanderpas commented on 2022Swerve/src/main/java/frc/robot/OI.java
> +            (1 - curvature) * input));
Comments showing a prettier version of the equation your using, and short explanation of it should get added.

2022-10-07 00:06 UTC, azvanderpas commented on 2022Swerve/src/main/java/frc/robot/OI.java
> +    }
Is this class needed?

2022-10-07 00:06 UTC, azvanderpas commented on 2022Swerve/src/main/java/frc/robot/subsystems/SwerveSubsystem.java
> +        double scale = Math.min(k * DriveConstants.kPhysicalMaxSpeed / realMaxSpeed, 1);
Does ```kPhysicalMaxSpeed``` make sense here even in the case that ```k``` comes from ```rotationalK```?
This whole method could use some comments about what math is being done here

2022-10-07 00:06 UTC, azvanderpas commented on 2022Swerve/src/main/java/frc/robot/subsystems/SwerveSubsystem.java
> +        this.normalizeDrive(desiredStates, DriveConstants.kDriveKinematics.toChassisSpeeds(desiredStates));
A comment for future reference about why ```desatureWheelSpeeds``` isn't sufficient here would probably be good.

2022-10-07 15:12 UTC, zbrotherton2158 commented on 2022Swerve/src/main/java/frc/robot/OI.java
> +            (1 - curvature) * input));
Further explanation on control curves, how they work, and an online graphing calculator representation are all in the swerve research document, but I did add an explanation of what each variable does, and wrote a more understandable version of the equation within the comments

2022-10-07 15:14 UTC, zbrotherton commented on 2022Swerve/src/main/java/frc/robot/OI.java
> +    }
The class is there to show intention of containing controls for the operator within a separate class

2022-10-13 22:20 UTC, adamzvp approved these changes

2022-10-13 22:23 UTC, azvanderpas approved these changes

2022-10-13 22:31 UTC, merged